Feature/update documentation v2.0
digin-energi/Grunnprofil pull request #200
Opened 2022-09-14 14:34 UTC by EmilieSkog

2022-09-14 19:54 UTC, Sveino requested changes

2022-09-14 19:54 UTC, Sveino commented on DIGIN10/v2.0/docs/ModelingGuide.adoc
>  The purpose of this document is to provide the necessary information to model a network according to the DIGIN10 model.
use "electrical power system" or "electrical power grid" instead of "network"

2022-09-14 19:54 UTC, Sveino commented on DIGIN10/v2.0/docs/ModelingGuide.adoc
> +Will be included in a later version of the DIGIN10 model.
```suggestion
Will be included in a later version of the DIGIN10 model. In this version it is model as Breaker.
```

2022-09-14 19:54 UTC, Sveino commented on DIGIN10/v2.0/docs/ModelingGuide.adoc
>  Substation is used to model cable cabinets in the LV files in CIM16, this is subject to change in CIM17.
```suggestion
Substation is used to model cable cabinets in the LV files. This is an issues and might be changed in upcoming version.
```

2022-09-14 19:54 UTC, Sveino commented on README.md
> +
```suggestion
PATL = Permanent Admissible Transmission Loading
TATL = Temporarily Admissible Transmission Loading
```

2022-09-14 19:54 UTC, Sveino commented on README.md
> +DIGIN10-24-v1.0 - Power flow and simulation utilization using CGMES v2.4 (CIM16).
```suggestion
DIGIN10-24-v1.0 - A 40 bus power flow case for MV and LV according to CGMES v2.4 (CIM16). Kept in this release to show the transition.
```

2022-09-14 19:54 UTC, Sveino commented on README.md
> +DIGIN10-30-v2.0 - Conversion of DIGIN10-24-v1.0 to CGMES v3.0 (CIM17).
```suggestion
DIGIN10-30-v2.0 - A 40 bus power flow case for MV and LV according to CGMES v3.0 (CIM17). A release to show the transformation from CGMES v2.4 to CGMES v3.0. 
```

2022-09-14 19:54 UTC, Sveino commented on README.md
> +CGMES v3.0 using CIM17 for MV and LV grid.
```suggestion
 A 40 bus power flow case for MV and LV according to CGMES v3.0 (CIM17). Including two Model Authority Set (MAS), bilateral boundaries and reference data. The solution is done on the merged (MV1+LV1).
```

2022-09-14 19:54 UTC, Sveino commented on README.md
>    - All files are CIM.XML files
```suggestion
  - All instance files are according to CIMXML format (IEC 61970-552) which is based on RDF XML.
```

2022-09-15 08:07 UTC, EmilieSkog commented on README.md
> +DIGIN10-24-v1.0 - Power flow and simulation utilization using CGMES v2.4 (CIM16).
Added, but will change "Kept in this release to show the transition" to "Kept in v2.0 release to show the transition"

2022-09-15 08:16 UTC, Sveino approved these changes

2022-09-15 08:44 UTC, merged